### PR TITLE
layer: Implement BBFILES_DYNAMIC to handle dynamic-layers

### PR DESCRIPTION
**Pull request by texierp**
Since we have BBFILES_DYNAMIC to activate content only
when some other layers are present (see: https://www.yoctoproject.org/docs/latest/ref-manual/ref-manual.html#var-BBFILES_DYNAMIC)

BBFILES_DYNAMIC can be used to handle
meta-atmel's dynamic-layers (instead of BBFILES).

Signed-off-by: Pierre-Jean TEXIER <texier.pj2@gmail.com>

### CODE REVIEW

**Comment by alexandrebelloni** [comment]
Seems good to me. I would have preferred not having to move everything in dynamic-layers but other layers are doing it that way.

**Comment by texierp** [comment]
Thanks for your feedback @alexandrebelloni
Indeed, it seems better to have only one dir to handle dynamic layers.

**Comment by noglitch** [comment]
I only add it to the sumo branch: rocko is in maintenance on our side, so I don't merge such a "big" change.
Thank you for your help. Best regards,
  Nicolas

**Comment by texierp** [comment]
For sure, no problem I understand :)
Thanks to you Nicolas, BR

/Pierre-Jean

**Pull request closed without merging**
