### PR TITLE
cryptoauthlib: Removed meta-aws dependency

### PR DESCRIPTION
**Pull request by colin-pm**
Currently the cryptoauthlib recipe is only enabled if meta-aws is
included.  There are use cases where crytpoauthlib may be used with PKI
that isn't related to AWS Greengrass.

The recipes-security directory in the aws dynamic layer was moved to the
base directory so cryptoauthlib can be used without the meta-aws layer.

Signed-off-by: Colin McAllister <colinmca242@gmail.com>

### CODE REVIEW

**Comment by colin-pm** [comment]
@codrin989 My commit message was probably unclear, but I moved the whole recipes-security directory from dynamic-layer/aws-layer to the base directory, so cryptoauthlib.module should be moved.

I would be happy to move the python3-cryptoauthlib recipe out of the aws dynamic layer as well.

**Comment by codrin989** [comment]
You are right, my mistake. The commit message is fine. Just include also the python-cryptoauthlib. Thanks!

**Comment by colin-pm** [comment]
Python-crytpoauthlib has been moved.

**Comment by codrin989** [comment]
Thanks!

**Pull request merged**
