### PR TITLE
mxt-app: Fix build with -fno-common

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
Please. cherry-pick it into master as well

**Comment by kraj** [comment]
ping

**Comment by noglitch** [comment]
mxt-app has just been fixed, we can update the recipe with new commit SRCREV.
I agree with plplot patch: @codrin989 okay to cherry-pick?

**Comment by codrin989** [comment]
sure, I will bump mxt-app to latest SHA to have the fix and cherry-pick the rest of the patches. Thanks @kraj !

**Pull request closed without merging**
