### PR TITLE
conf/machine*: remove deprecated MACHINE_FEATURES 

### PR DESCRIPTION
**Pull request by texierp**
This update remove several deprecated module in MACHINE_FEATURES.

### CODE REVIEW

**Comment by alexandrebelloni** [comment]
Seems good to me

**Comment by texierp** [comment]
Thanks Alexandre.
This PR is also available for the last branch (rocko).

**Comment by noglitch** [comment]
added the ptc ek board changes for rocko and merge on both rocko and morty branches.
Thanks Pierre-Jean!
Regards,
  Nicolas

**Comment by texierp** [comment]
Thanks Nicolas.

Regards
Pierre-Jean

**Pull request merged**
