### PR TITLE
recipes: bump libegt/libplanes

### PR DESCRIPTION
**Pull request by texierp**

### CODE REVIEW

**Comment by codrin989** [comment]
Thank you for your pull request!
I get some errors when I try to build egt-launcher. Is it working on your side?

**Comment by texierp** [comment]
Argf Indeed, I missed to push the bump for `egt-launcher` :(

Should be fixed now

**Comment by codrin989** [comment]
egt-samples also needs to be updated. It should be the last dependency. Thanks!

**Comment by texierp** [comment]
Thanks @codrin989 , PR updated ;)

**Comment by codrin989** [comment]
Thanks Pierre!

**Pull request merged**
