### PR TITLE
Kirkstone cleanup

### PR DESCRIPTION
**Pull request by mdavis777**

### CODE REVIEW

**Comment by mdavis777** [comment]
Looking at the current state of master vs dunfell I am guessing kirkstone work is not currently supported.  Do you have an ETA on when a full kirkstone release can be expected?

**Comment by gehariprasath** [comment]
> Looking at the current state of master vs dunfell I am guessing kirkstone work is not currently supported. Do you have an ETA on when a full kirkstone release can be expected?

Hello Michael

We have already started the migration process and our plan is to include it in our next Linux4Sam release planned in end of October or early November time frame.

Regards,
Hari

**Comment by elockman** [comment]
Thank you. I'm also looking forward to the migration.

**Comment by Dharma-B** [comment]
Since we have already migrated to "kirkstone", these changes are not required to be merged with the "master" branch.
@gehariprasath Can we close this pull request?

**Comment by elockman** [comment]
Please close. Thank you for the update!

**Pull request closed without merging**
