### PR TITLE
videoplayer: Delete 1.8 recipe

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by RazvanStef** [comment]
Hello,

Thank you for the PR.

As you can see on the thud branch, I added a recipe that makes the same thing. I'll try to merge as much as possible from thud to master and, afterwards, pick your PR, if it is still needed.

Thank you,
Razvan

**Comment by kraj** [comment]
@RazvanStef I See that warrior is more uptodate then master. I think it will be good to keep master the first entry point for fixes and then backported to layers as needed. Then you can branch off release branches from master as the yocto releases happen

**Comment by RazvanStef** [comment]
Thank you for the suggestion. I'll try to sync them.

**Comment by kraj** [comment]
thanks for updating master. I have rebased this PR on top of it now

**Pull request merged**
