### PR TITLE
Update qmlbrowser_1.6.bb

### PR DESCRIPTION
**Pull request by koansoftware**
Package checksum changed

### CODE REVIEW

**Comment by alexandrebelloni** [comment]
Seems good to me. It would be better to tag qmlbrowser to avoid that in the future.

**Comment by gizero** [comment]
Even better, why not switching this (and many other recipes in this layer that looks similar) to use the git fetcher instead? Just pointing to tagged archives won't completely solve the issue of changing checksums, since Github archives are known to be regenerated from time to time and that process isn't deterministic w.r.t to checksum (see many similar suggested changes against meta-openembedded metadata)

**Comment by noglitch** [comment]
@alexandrebelloni, @gizero : the issue that I see is that git ports are rarely opened within company networks. We'd better standardize on git over https.
What about buildroot according to this matter?

**Comment by alexandrebelloni** [comment]
With buildroot you can use <package>_SITE_METHOD = git to force git over https

**Comment by noglitch** [comment]
Okay. We move to v1.6 of this package for upcoming release.
Indeed we need to think about this at the light of this information. In terms of availably of ports open in company networks and amount of data to download.
Will likely be addressed for Linux4SAM 6.0 mid-2018ish.

**Comment by gizero** [comment]
By "using the git fetcher" I meant fetching from a git repository as opposed to downloading tar archives, as we currently do, with the well known checksum issues mentioned above. Fetching from repos does not impose using the `git` wire protocol at all. Protocol can be specified by the `protocol=` option in SRC_URI and, since GitHub exposes `https` clone urls, that should be the obvious choice IMHO.

Something like this should work:
```
SRC_URI = "git://github.com/linux4sam/qml-browser.git;protocol=https"
PV = "1.6+git${SRCPV}"
SRCREV = "pinned-commit-sha-goes-here"
```

**Pull request closed without merging**
