### PR TITLE
Update for Krogoth

### PR DESCRIPTION
**Pull request by alexandrebelloni**
Update meta-atmel for krogoth

### CODE REVIEW

**Comment by noglitch** [comment]
we still need the atmel firmware recipe as the new firmware are not included yet in linux-firmware... and we need them for the latest source code...

**Comment by alexandrebelloni** [comment]
From my test, the 3 binaries were the same did I miss some?

**Comment by noglitch** [comment]
I mean the new firmwares that are from v > v11 are not in linux-firmware yet. They weren't included in the jethro branch but we need them for our next release in the coming days...

**Comment by alexandrebelloni** [comment]
I updated the branch to remove those commits

**Pull request merged**
