### PR TITLE
Update git:// to https:// for at91bootstrap repo

### PR DESCRIPTION
**Pull request by rob-baily**
See https://github.blog/2021-09-01-improving-git-protocol-security-github/ for reason

### CODE REVIEW

**Comment by rob-baily** [comment]
Using this as a build started but filed later on with what seems to be an unrelated error.

```
ERROR: sam-ba-native-3.3.1-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export PATH="/home/ubuntu/poky/scripts/native-intercept:/home/ubuntu/poky/build-tworx  -initramfs/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/ubuntu/poky/scripts:/home/ubuntu/poky/build-tworx-initramfs/tmp/work/x86_64-linux/sam-ba-native/3.3.1-r0/recipe-sysroot-n  ative/usr/bin/x86_64-linux:/home/ubuntu/poky/build-tworx-initramfs/tmp/work/x86_64-linux/sam-ba-native/3.3.1-r0/recipe-sysroot-native/usr/bin:/home/ubuntu/poky/build-tworx-initramfs/  tmp/work/x86_64-linux/sam-ba-native/3.3.1-r0/recipe-sysroot-native/usr/sbin:/home/ubuntu/poky/build-tworx-initramfs/tmp/work/x86_64-linux/sam-ba-native/3.3.1-r0/recipe-sysroot-native  /usr/bin:/home/ubuntu/poky/build-tworx-initramfs/tmp/work/x86_64-linux/sam-ba-native/3.3.1-r0/recipe-sysroot-native/sbin:/home/ubuntu/poky/build-tworx-initramfs/tmp/work/x86_64-linux  /sam-ba-native/3.3.1-r0/recipe-sysroot-native/bin:/home/ubuntu/poky/bitbake/bin:/home/ubuntu/poky/build-tworx-initramfs/tmp/hosttools"; export HOME="/home/ubuntu"; /usr/bin/env wget   -t 2 -T 30 --passive-ftp --no-check-certificate -P /home/ubuntu/poky/build-tworx-initramfs/downloads 'https://github.com/atmelcorp/sam-ba/releases/download/v3.3.1/sam-ba_3.3.1-linux_  x86_64.tar.gz' --progress=dot -v failed with exit code 8, no output
ERROR: sam-ba-native-3.3.1-r0 do_fetch: Fetcher failure for URL: 'https://github.com/atmelcorp/sam-ba/releases/download/v3.3.1/sam-ba_3.3.1-linux_x86_64.tar.gz'. Unable to fetch URL   from any source.

Seems that https://github.com/atmelcorp/sam-ba/releases/download/v3.3.1/sam-ba_3.3.1-linux_x86_64.tar.gz returns a 404 error.  Do not know why this happens now or what to do about it.
```

**Comment by texierp** [comment]
Hello @rob-baily ,

Can you check with: https://github.com/linux4sam/meta-atmel/pull/206

Thanks !

**Comment by rob-baily** [comment]
> Hello @rob-baily ,
> 
> Can you check with: #206
> 
> Thanks !

Looks like #206 does resolve the sam-ba download issue.  Thank you!  

Running through the rest of our build with that and the change in this pull request.  Will let you know if I see any more issues with it related to URLs.

**Comment by noglitch** [comment]
I think it's not the way to fix this issue. You must change the "protocol=git" to "protocol=https". The "fetcher" should stay the git fetcher.
Best regards,
  Nicolas

**Pull request closed without merging**
