### PR TITLE
linux firmware: install all tools files

### PR DESCRIPTION
**Pull request by rzr**
Change-Id: I94dbadcb2fdcce35aeca9b3f9f2152efa8b29989
Or
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

### CODE REVIEW

**Comment by noglitch** [comment]
Hi Philippe,
What is the use of this tool directory?

**Comment by rzr** [comment]
seems some windows utility, unsure it will work on wine but it's part of the firmware package since it's installed as error report in commit message.


atmel-wireless-firmware/0.0+gitAUTOINC+63324e760a-r0/sysroot-destdir/lib/firmware/atmel/tools/README.txt  
'gain_builder' utility can change RF Tx gain value fixed in firmware file to the required gain.

How to way.
        1. modify value in cvs file.
        2. execute gain_builder.exe on console of MS windows PC.
          ex) gain_builder -hp xxx.csv -fb wilc1003_firmware.bin
        3. overwrite bin file existed in linux's firmware folder with above modifed binary.

Caution :
        this function can be applied only for wilc1003_firmware(wilc1000B chipset).

**Comment by rzr** [comment]
Do you prefer files to be installed or removed ?


Here is the error message I am facing on dizzy branch ,

```
cd /home/philippe/local/src/meta-yocto-demos/build-sama5d4-xplained && time bitbake atmel-xplained-lcd-demo-image
Loading cache: 100% |##########################################################################################################################################################################################################################################| ETA:  00:00:00
Loaded 2106 entries from dependency cache.
Parsing recipes: 100% |########################################################################################################################################################################################################################################| Time: 00:00:01
Parsing of 1649 .bb files complete (1645 cached, 4 parsed). 2109 targets, 94 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.24.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-14.04"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "sama5d4-xplained"
DISTRO            = "poky"
DISTRO_VERSION    = "1.7.3"
TUNE_FEATURES     = "arm armv7a vfp thumb neon callconvention-hard cortexa5"
TARGET_FPU        = "vfp-neon"
meta              
meta-yocto        
meta-yocto-bsp    = "(detachedfrom8ef55cc):8ef55cc0da13c96349f665987f2bcf9e64eebf8a"
meta-atmel        = "(nobranch):71ab54fda0ce05f46d89575f458f9135f37f2c16"
meta-qt5          = "(nobranch):adeca0db212d61a933d7952ad44ea1064cfca747"
.                 = "sandbox/pcoval/meta/atmel/dizzy:982b57ec2fc53407b3b52daf247b7cfcdbc316a2"
meta-python       
meta-networking   
meta-oe           = "(nobranch):e06b3c88e8cd1d151d9f8aa5bfc28f0b5ca52bd9"

NOTE: Preparing runqueue
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
WARNING: python-pip: No generic license file exists for: GPL in any provider
ERROR: QA Issue: atmel-wireless-firmware: Files/directories were installed but not shipped
  /lib/firmware/atmel/tools
  /lib/firmware/atmel/tools/README.txt
  /lib/firmware/atmel/tools/gain_setting_hp_ex.csv
  /lib/firmware/atmel/tools/gain_builder.exe [installed-vs-shipped]
Currently 2 running tasks (1771 of 3499):
0: glibc-2.20-r0 do_populate_sysroot (pid 21386)
```

**Comment by noglitch** [comment]
I'd say that we can remove these tools from the embedded side.

Bye,
  Nicolas.

**Comment by noglitch** [comment]
I removed the "tools" directory in the 14.1 recipe (all other recipes removed actually).

**Comment by rzr** [comment]
Thanks I will try again  on master and deezy branches

**Comment by noglitch** [comment]
Hi @rzr, I'm not sure master is updated though.
We'll have to port all the krogoth updates to master to prepare next version...

**Pull request closed without merging**
