### PR TITLE
dt-overlay-at91: do not install the FIT image source file on /boot

### PR DESCRIPTION
**Pull request by texierp**
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>

### CODE REVIEW

**Comment by codrin989** [comment]
Hi Pierre,
Any specific reason why you don't want the .its files there?

**Comment by texierp** [comment]
Hi @codrin989,
In fact, it makes no sense to deploy the source file on the target, no ?

**Comment by codrin989** [comment]
Fair point. I think that the idea was to be able to create and add overlays on target, reboot and have the new overlays applied. I will let this open to discussion for a few days. If no one complains, we can remove it, perhaps along with the .dtbo files.

**Comment by noglitch** [comment]
.its file and .dtbo files are very different, with very different purpose while being present on a target running system.
Overlays fragments can be loaded at runtime with proper kernel configuration and configfs (/sys/kernel/config/device-tree/overlays), so I would keep them, for future use.
For .its, like you said, it can be handy for re-genrating a new .itb from the target. I see this as a fairly exceptional use-case. So I agree with @texierp.
Like you said @codrin989, let's keep the discussion open for a couple of days...

**Comment by noglitch** [comment]
Sorry @texierp, I changed my mind and edited my previous message: be informed ;-)

**Comment by texierp** [comment]
> Sorry @texierp, I changed my mind and edited my previous message: be informed ;-)

No problem ;), thanks for the update @noglitch

**Comment by codrin989** [comment]
@texierp , it looks like it is possible to rebuild the .itb file on target, using dumpimage. I don't think we can extract the .its file from the .itb, so it makes sense to keep the .its file if someone needs to quickly add an overlay. Thanks!

**Comment by texierp** [comment]
Sure ! no problem ;)

**Pull request closed without merging**
