### PR TITLE
Bring changes to build with clang15 and master branch of oe-core

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by ldesroches** [comment]
Hi,

Concerning EGT, is this move to c++17 mandatory? There is a fallback if the experimental file system is not detected. Maybe this fallback is not working as expected... We are considering making this move but we don't want to do it in a rush.

Regards

**Comment by kraj** [comment]
> Hi,
> 
> Concerning EGT, is this move to c++17 mandatory? There is a fallback if the experimental file system is not detected. Maybe this fallback is not working as expected... We are considering making this move but we don't want to do it in a rush.

This was a path to fix build with clang 15+ where libc++ has started to drop older features, if we can fix it in other ways thats ok too.

> 
> Regards

**Comment by kraj** [comment]
Can you cherry-pick the layer compat patches ? they are now needed

**Comment by noglitch** [comment]
@Dharma-B , @gehariprasath : some patches to queue for the dunfell branch before that we move "master" to kirkstone, probably

**Comment by gehariprasath** [comment]
Noted, the layer compat 

> Can you cherry-pick the layer compat patches ? they are now needed

We will apply the same and the other patch for cryptoauthlib after review.

**Comment by gehariprasath** [comment]
@kraj The cryptoauthlib has the manual document which is part of the repository, hence we cannot skip it. Installing git-lfs in the host machine is an easier option.

**Comment by kraj** [comment]
> @kraj The cryptoauthlib has the manual document which is part of the repository, hence we cannot skip it. Installing git-lfs in the host machine is an easier option.

OK, I have dropped the concerned patch from pull here.

**Comment by noglitch** [comment]
I think this one can be closed as well.

**Comment by kraj** [comment]
@noglitch I still have egt patches but I will open a new PR for that

**Pull request closed without merging**
