### PR TITLE
qtquick1: Delete recipe

### PR DESCRIPTION
**Pull request by kraj**
Depend on one from upstream meta-qt5

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by alexandrebelloni** [comment]
Well, removing that recipe will break the demo. I've sent a patch to meta-qt5 multiple times without any answer...

**Comment by kraj** [comment]
@alexandrebelloni ok. Can you point me to the uptream patch request?

**Comment by alexandrebelloni** [comment]
Sure: https://patchwork.openembedded.org/patch/125989/

I've just realized it has been taken in meta-qt5 master but it wasn't backported on krogoth

**Comment by kraj** [comment]
OK then reply to the thread requesting a backport to krogoth. @noglitch should merge this patch to master here.

**Comment by alexandrebelloni** [comment]
Now that it has been backported, it can be applied on both master and krogoth.

**Pull request merged**
