### PR TITLE
egt-media: Check for license befor including gstreamer1.0-libav

### PR DESCRIPTION
**Pull request by kraj**
It depends on ffmpeg which has implications on commercial use
check if user has checked it and enabled it

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by codrin989** [comment]
@SandeepSM @ldesroches @noglitch is egt-media working without gstreamer1.0-libav ?

**Comment by kraj** [comment]
> @SandeepSM @ldesroches @noglitch is egt-media working without gstreamer1.0-libav ?

it is not removing it, its just making it clear on license restrictions. So if it works or not is a different question

**Comment by codrin989** [comment]
egt-media 's runtime dependency to gstreamer1.0-libav is removed if "commercial" is not present in LICENSE_FLAGS_WHITELIST. If gstreamer1.0-libav is a must for egt-media and gstreamer1.0-libav is not added, there is no point in keeping egt-media packet.

**Comment by kraj** [comment]
right, however it will be flagged and removed from bitbake parse with this change.

**Comment by codrin989** [comment]
Pushed to dunfell/gatesgarth/master. Thanks!

**Pull request merged**
